language: node_js

node_js:
  - node

before_script:
  - source travis-functions.sh
  - checkconflicts
  - sudo pip install -U pip
  - sudo pip install pre-commit
  - pre-commit run --all-files

script:
  - npm install
  - ng build &
  - sleep 10
